name: Deploy Azure Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build
      run: dotnet publish FunctionApp1/Eastern-Drayage-AzureFunctions.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: AmsDevFunction
        package: ./publish
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
